version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    parameters:
      registery:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build and deploy docker image"
          command: |
            docker build --cache-from=app -t app .
            docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            docker tag app << parameters.registery >>:${CIRCLE_SHA1}
            docker push << parameters.registery >>:${CIRCLE_SHA1}
  publish-dev:
    docker:
      - image: tribeplatform/cli:1.0.0
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    environment:
      DOCKER_REGISTERY: tribeplatform/slack
    steps:
      - checkout
      - run:
          name: "Deploy app on DEV environment"
          command: |
            ops init -i -e ermia@bettermode.com -u $OPS_USERNAME -p $OPS_PASSWORD
            ops app create -n slack -i $DOCKER_REGISTERY:$CIRCLE_SHA1
            ops service deploy -s slack -i $DOCKER_REGISTERY:$CIRCLE_SHA1
  publish-prod:
    docker:
      - image: tribeplatform/cli:1.0.0
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    environment:
      DOCKER_REGISTERY: tribeplatform/slack
    steps:
      - checkout
      - run:
          name: "Deploy app on PRD environment"
          command: |
            ops init -i -e ermia@bettermode.com -u $OPS_USERNAME -p $OPS_PASSWORD
            ops app create -n slack -i $DOCKER_REGISTERY:$CIRCLE_SHA1 -e prd
            ops service deploy -s slack -e prd -i $DOCKER_REGISTERY:$CIRCLE_SHA1
workflows:
  app:
    jobs:
      - build:
          registery: tribeplatform/slack
          context: App
          filters:
            branches:
              only:
                - master
      - publish-dev:
          context: App
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires:
            - build
      - publish-prod:
          context: App
          requires:
            - hold
          filters:
            branches:
              only:
                - master
# VS Code Extension Version: 1.5.1